# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

alias tmux="TERM=screen-256color-bce tmux"
if [ "$TMUX" = "" ]; then tmux; fi

# Path to your oh-my-zsh installation.
export ZSH=/home/amustafa/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="sonicradish"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
# autoenv: Activates autoenv or reports its failure
# autojump: activates autojump
# autopep8: tab completion file
# bgnotify: notifications for long running commands
# celery: tab completion file
# command-not-found: suggests something in apt if command not found
# compleat: 
#       Generate tab completion for any shell command by specifying its usage in a familiar 
#       manpage-like format.
# copybuffer: 
#       binds the ctrl-o keyboard shortcut to a command that copies the text that is currently typed in 
#       the command line 
# copydir:  Copies the pathname of the current directory
# extract:  extracts the archive file you pass it, and it supports a wide variety of archive filetypes.
# globalias: Expands all glob expressions, subcommands and aliases (including global).
# httpie: add completion for httpie
# jsontools: tools for jsondata
# jump: Easily jump around the file system by manually adding marks
# geeknote: terminal evernote
# nmap: nmap aliases plugin
# pep8 code completion for pep8
# sudo: esc-esc will insert sudo in front of command
# taskwarrior: completion for taskwarrior
# z: jump around file directory
# last-working-directory: keeps track of the last directory and lwd to it
# colorize: colorize_via_pygmentize
# golang: adds completion for go
#MY PLUGINS
# my-aliases

plugins=(my-aliases sudo copybuffer copydir copyfile git github gitflow gitignore cp direnv autojump autopep8 command-not-found pep8 bgnotify extract jsontools virtualenvwrapper vi-mode pip command-not-found tmux urltools wd znt web-search copyfile rsync httpie jump nmap pylint taskwarrior tig z last-working-directory colorize golang)

source $ZSH/oh-my-zsh.sh

######## User configuration ##########
# Java
export JAVA_HOME="$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')"

# Spark
export SPARK_HOME=/home/amustafa/opt/spark
export PYSPARK_PYTHON=/home/amustafa/opt/anaconda3/bin/python
export PATH="$SPARK_HOME/bin:$PATH"
#export PYSPARK_DRIVER_PYTHON=/opt/anaconda3/bin/ipython
# export PYTHONPATH="$SPARK_HOME/python:/srv/spark/python/lib/py4j-0.10.4-src.zip:$PYTHONPATH"
# export PYSPARK_SUBMIT_ARGS="--master spark://192.168.1.16:7077"
# spark://localhost:7077"

# Hadoop
export HADOOP_HOME=/home/amustafa/opt/hadoop
export PATH=$PATH:$HADOOP_HOME/bin

# Anaconda
#   Keep Last so it's libraries are first.
export PATH=/home/amustafa/opt/anaconda3/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="vim ~/.oh-my-zsh"
#

export EDITOR='nvim'

# eval "$(direnv hook zsh)"
# eval "$(fasd --init auto)"
