" To convert to neovm: https://arusahni.net/blog/2015/04/switching-to-neovim-part-2.html
set nocompatible              " be iMproved, required
filetype off                  " required

if has('nvim')
    let s:editor_root=expand("$NVIM_CONFIG_HOME")
else
    let s:editor_root=expand("~/.vim")
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'



Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'vim-scripts/mru.vim'
Plugin 'easymotion/vim-easymotion'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-obsession'
Plugin 'flazz/vim-colorschemes'
Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-misc'
Plugin 'xolox/vim-session'
Plugin 'mileszs/ack.vim'
Plugin 'lervag/vimtex'
Plugin 'SirVer/ultisnips'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'xolox/vim-colorscheme-switcher'

Plugin 'amix/open_file_under_cursor.vim'
Plugin 'honza/vim-snippets' " contains snippet files
Plugin 'zenbro/mirror.vim'
Plugin 'vim-scripts/tlib'
Plugin 'godlygeek/tabular'
Plugin 'tpope/vim-abolish'
Plugin 'marcweber/vim-addon-mw-utils'
Plugin 'tpope/vim-commentary'  " comment stuff out
Plugin 'terryma/vim-expand-region' " select increasingly larger regions
Plugin 'maxbrunsfeld/vim-yankstack'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'  " allows some plugins actions to repeat with .
Plugin 'terryma/vim-multiple-cursors'  "sublime-like cursor behavior
Plugin 'michaeljsmith/vim-indent-object' 
Plugin 'airblade/vim-gitgutter'
Plugin 'Rykka/riv.vim'
Plugin 'Rykka/InstantRst'

if !has('nvim')
    Plugin 'scrooloose/syntastic'
    Plugin 'ivanov/vim-ipython'
    Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
    Plugin 'Valloric/YouCompleteMe'
endif


if has('nvim')
    Plugin 'w0rp/ale'
    "Plugin 'neomake/neomake'
    Plugin 'roxma/nvim-yarp'
    Plugin 'roxma/vim-hug-neovim-rpc'
    Plugin 'davidhalter/jedi-vim'
    Plugin 'shougo/deoplete.nvim'
    Plugin 'zchee/deoplete-jedi'
    Plugin 'itchyny/lightline.vim'
    Plugin 'maximbaz/lightline-ale'
    "Plugin 'vim-airline/vim-airline'   " replaced with lightline
    "Plugin 'vim-airline/vim-airline-themes'
    " Plugin 'bfredl/nvim-ipy'
    Plugin 'hkupty/iron.nvim'
endif

" Language Specific formatters and syntax highlighters
Plugin 'google/yapf'
Plugin 'chr4/nginx.vim'
Plugin 'tomlion/vim-solidity'
Plugin 'groenewege/vim-less'  " syntax for less
Plugin 'fatih/vim-go'
Plugin 'nvie/vim-flake8'
Plugin 'plasticboy/vim-markdown'  " must have tabular before this. Style for Markdown

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


"""Amix vimrc config"""""""""""
set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
"source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

try
source ~/.vim_runtime/my_plugins_config.vim
catch
endtry
""""""""""""""""""""""""""""""""""""""""'
